import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root', // Permite que o serviço seja acessível em toda a aplicação
})
export class AccomodationService {
  private accommodations = [
    {
      ID: 1,
      Tipo: 'Casa',
      Descricao: 'Casa aconchegante com jardim e piscina.',
      Capacidade: 6,
      'Tipo de logradouro': 'Rua',
      Logradouro: 'das Flores',
      Número: 123,
      Bairro: 'Centro',
      Cidade: 'São Paulo',
      Estado: 'SP',
      Complemento: 'Casa 1',
      CEP: '01001-000',
      Latitude: -23.5505,
      Longitude: -46.6333,
      'Preço por noite/diária': 300.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Vistas incríveis',
    },
    {
      ID: 2,
      Tipo: 'Apartamento',
      Descricao: 'Apartamento moderno com vista para o mar.',
      Capacidade: 4,
      'Tipo de logradouro': 'Avenida',
      Logradouro: 'Beira Mar',
      Número: 456,
      Bairro: 'Praia do Canto',
      Cidade: 'Vitória',
      Estado: 'ES',
      Complemento: 'Apto 302',
      CEP: '29055-123',
      Latitude: -20.2976,
      Longitude: -40.2958,
      'Preço por noite/diária': 450.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-1.2.1&auto=format&fit=crop&w=1353&q=80',
      Categoria: 'Nas alturas',
    },
    {
      ID: 3,
      Tipo: 'Quarto de hotel',
      Descricao: 'Quarto confortável com café da manhã incluso.',
      Capacidade: 2,
      'Tipo de logradouro': 'Rua',
      Logradouro: 'São Bento',
      Número: 789,
      Bairro: 'Centro',
      Cidade: 'Rio de Janeiro',
      Estado: 'RJ',
      Complemento: 'Quarto 101',
      CEP: '20040-002',
      Latitude: -22.9068,
      Longitude: -43.1729,
      'Preço por noite/diária': 200.0,
      Status: 'Reservado',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Pousadas',
    },
    {
      ID: 4,
      Tipo: 'Casa',
      Descricao: 'Casa de campo com churrasqueira e lago.',
      Capacidade: 8,
      'Tipo de logradouro': 'Estrada',
      Logradouro: 'da Serra',
      Número: 101,
      Bairro: 'Serra Azul',
      Cidade: 'Belo Horizonte',
      Estado: 'MG',
      Complemento: '',
      CEP: '31000-000',
      Latitude: -19.9167,
      Longitude: -43.9345,
      'Preço por noite/diária': 500.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Fazendas',
    },
    {
      ID: 5,
      Tipo: 'Apartamento',
      Descricao: 'Apartamento compacto próximo ao metrô.',
      Capacidade: 2,
      'Tipo de logradouro': 'Rua',
      Logradouro: 'das Palmeiras',
      Número: 234,
      Bairro: 'Moema',
      Cidade: 'São Paulo',
      Estado: 'SP',
      Complemento: 'Apto 501',
      CEP: '04078-000',
      Latitude: -23.6,
      Longitude: -46.6667,
      'Preço por noite/diária': 250.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-1.2.1&auto=format&fit=crop&w=1353&q=80',
      Categoria: 'Cidades icônicas',
    },
    {
      ID: 6,
      Tipo: 'Quarto de hotel',
      Descricao: 'Quarto luxuoso com vista para a montanha.',
      Capacidade: 2,
      'Tipo de logradouro': 'Avenida',
      Logradouro: 'das Montanhas',
      Número: 567,
      Bairro: 'Alto da Serra',
      Cidade: 'Petrópolis',
      Estado: 'RJ',
      Complemento: 'Quarto 201',
      CEP: '25680-000',
      Latitude: -22.505,
      Longitude: -43.1789,
      'Preço por noite/diária': 350.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Vistas incríveis',
    },
    {
      ID: 7,
      Tipo: 'Casa',
      Descricao: 'Casa espaçosa com quintal grande.',
      Capacidade: 10,
      'Tipo de logradouro': 'Rua',
      Logradouro: 'dos Coqueiros',
      Número: 890,
      Bairro: 'Jardim Botânico',
      Cidade: 'Curitiba',
      Estado: 'PR',
      Complemento: '',
      CEP: '80000-000',
      Latitude: -25.4296,
      Longitude: -49.2713,
      'Preço por noite/diária': 600.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Casas de terra',
    },
    {
      ID: 8,
      Tipo: 'Apartamento',
      Descricao: 'Apartamento com vista para o parque.',
      Capacidade: 3,
      'Tipo de logradouro': 'Rua',
      Logradouro: 'das Árvores',
      Número: 345,
      Bairro: 'Jardins',
      Cidade: 'São Paulo',
      Estado: 'SP',
      Complemento: 'Apto 102',
      CEP: '01415-000',
      Latitude: -23.5675,
      Longitude: -46.6733,
      'Preço por noite/diária': 400.0,
      Status: 'Reservado',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Design',
    },
    {
      ID: 9,
      Tipo: 'Quarto de hotel',
      Descricao: 'Quarto econômico com Wi-Fi grátis.',
      Capacidade: 1,
      'Tipo de logradouro': 'Rua',
      Logradouro: 'das Oliveiras',
      Número: 678,
      Bairro: 'Centro',
      Cidade: 'Porto Alegre',
      Estado: 'RS',
      Complemento: 'Quarto 301',
      CEP: '90000-000',
      Latitude: -30.0346,
      Longitude: -51.2177,
      'Preço por noite/diária': 150.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1565329921943-7e537b7a2ea9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Pousadas',
    },
    {
      ID: 10,
      Tipo: 'Casa',
      Descricao: 'Casa de praia com acesso direto à areia.',
      Capacidade: 5,
      'Tipo de logradouro': 'Avenida',
      Logradouro: 'da Praia',
      Número: 112,
      Bairro: 'Praia do Sol',
      Cidade: 'Florianópolis',
      Estado: 'SC',
      Complemento: '',
      CEP: '88000-000',
      Latitude: -27.5945,
      Longitude: -48.5477,
      'Preço por noite/diária': 550.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Vistas incríveis',
    },
    {
      ID: 11,
      Tipo: 'Apartamento',
      Descricao: 'Apartamento com varanda gourmet.',
      Capacidade: 4,
      'Tipo de logradouro': 'Rua',
      Logradouro: 'dos Coqueirais',
      Número: 901,
      Bairro: 'Barra da Tijuca',
      Cidade: 'Rio de Janeiro',
      Estado: 'RJ',
      Complemento: 'Apto 401',
      CEP: '22790-000',
      Latitude: -22.9997,
      Longitude: -43.3656,
      'Preço por noite/diária': 480.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1505691938895-1758d7feb511?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Nas alturas',
    },
    {
      ID: 12,
      Tipo: 'Quarto de hotel',
      Descricao: 'Quarto familiar com duas camas de casal.',
      Capacidade: 4,
      'Tipo de logradouro': 'Avenida',
      Logradouro: 'das Estrelas',
      Número: 223,
      Bairro: 'Boa Viagem',
      Cidade: 'Recife',
      Estado: 'PE',
      Complemento: 'Quarto 501',
      CEP: '51000-000',
      Latitude: -8.1193,
      Longitude: -34.9038,
      'Preço por noite/diária': 280.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1565329921943-7e537b7a2ea9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Pousadas',
    },
    {
      ID: 13,
      Tipo: 'Casa',
      Descricao: 'Casa rústica com lareira.',
      Capacidade: 6,
      'Tipo de logradouro': 'Estrada',
      Logradouro: 'da Colina',
      Número: 334,
      Bairro: 'Vila Nova',
      Cidade: 'Gramado',
      Estado: 'RS',
      Complemento: '',
      CEP: '95670-000',
      Latitude: -29.3733,
      Longitude: -50.8764,
      'Preço por noite/diária': 700.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Fazendas',
    },
    {
      ID: 14,
      Tipo: 'Apartamento',
      Descricao: 'Apartamento pequeno próximo ao centro.',
      Capacidade: 2,
      'Tipo de logradouro': 'Rua',
      Logradouro: 'das Pedras',
      Número: 445,
      Bairro: 'Centro',
      Cidade: 'Salvador',
      Estado: 'BA',
      Complemento: 'Apto 201',
      CEP: '40000-000',
      Latitude: -12.9777,
      Longitude: -38.5016,
      'Preço por noite/diária': 220.0,
      Status: 'Disponível',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-1.2.1&auto=format&fit=crop&w=1353&q=80',
      Categoria: 'Cidades icônicas',
    },
    {
      ID: 15,
      Tipo: 'Quarto de hotel',
      Descricao: 'Quarto executivo com sala de reuniões.',
      Capacidade: 2,
      'Tipo de logradouro': 'Avenida',
      Logradouro: 'dos Negócios',
      Número: 556,
      Bairro: 'Centro',
      Cidade: 'Brasília',
      Estado: 'DF',
      Complemento: 'Quarto 601',
      CEP: '70000-000',
      Latitude: -15.7942,
      Longitude: -47.8822,
      'Preço por noite/diária': 400.0,
      Status: 'Em manutenção',
      Reservas: [],
      Imagem:
        'https://images.unsplash.com/photo-1565329921943-7e537b7a2ea9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      Categoria: 'Design',
    },
  ];
  getAccomodations() {
    return this.accommodations;
  }
}
